//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="Items", Namespace="http://www.techcenter.com/webservices/datacollection/", ItemName="Item")]
    public class Items : System.Collections.Generic.List<string>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CDCComponent", Namespace="http://www.techcenter.com/webservices/datacollection/")]
    public partial class CDCComponent : object
    {
        
        private string ProcessExceptionField;
        
        private string VINField;
        
        private string ComponentTypeCodeField;
        
        private ServiceReference.Attribute[] AttributesField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ProcessException
        {
            get
            {
                return this.ProcessExceptionField;
            }
            set
            {
                this.ProcessExceptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string VIN
        {
            get
            {
                return this.VINField;
            }
            set
            {
                this.VINField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ComponentTypeCode
        {
            get
            {
                return this.ComponentTypeCodeField;
            }
            set
            {
                this.ComponentTypeCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public ServiceReference.Attribute[] Attributes
        {
            get
            {
                return this.AttributesField;
            }
            set
            {
                this.AttributesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Attribute", Namespace="http://www.techcenter.com/webservices/datacollection/")]
    public partial class Attribute : object
    {
        
        private string NameField;
        
        private string ValueField;
        
        private string InstallTSField;
        
        private string ValidationCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string InstallTS
        {
            get
            {
                return this.InstallTSField;
            }
            set
            {
                this.InstallTSField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ValidationCode
        {
            get
            {
                return this.ValidationCodeField;
            }
            set
            {
                this.ValidationCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CheckComponentResult", Namespace="http://www.techcenter.com/webservices/datacollection/")]
    public partial class CheckComponentResult : object
    {
        
        private string ProcessExceptionField;
        
        private string VinField;
        
        private ServiceReference.CheckedComponent[] CheckedComponentsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ProcessException
        {
            get
            {
                return this.ProcessExceptionField;
            }
            set
            {
                this.ProcessExceptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Vin
        {
            get
            {
                return this.VinField;
            }
            set
            {
                this.VinField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public ServiceReference.CheckedComponent[] CheckedComponents
        {
            get
            {
                return this.CheckedComponentsField;
            }
            set
            {
                this.CheckedComponentsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CheckedComponent", Namespace="http://www.techcenter.com/webservices/datacollection/")]
    public partial class CheckedComponent : object
    {
        
        private string ComponentTypeCodeField;
        
        private string ValueField;
        
        private string ScanStatusField;
        
        private string ValidationCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ComponentTypeCode
        {
            get
            {
                return this.ComponentTypeCodeField;
            }
            set
            {
                this.ComponentTypeCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ScanStatus
        {
            get
            {
                return this.ScanStatusField;
            }
            set
            {
                this.ScanStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ValidationCode
        {
            get
            {
                return this.ValidationCodeField;
            }
            set
            {
                this.ValidationCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Versions", Namespace="http://www.techcenter.com/webservices/datacollection/")]
    public partial class Versions : object
    {
        
        private string WebServiceVersionField;
        
        private string DCWSLibVersionField;
        
        private string DCWSCOMVersionField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string WebServiceVersion
        {
            get
            {
                return this.WebServiceVersionField;
            }
            set
            {
                this.WebServiceVersionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string DCWSLibVersion
        {
            get
            {
                return this.DCWSLibVersionField;
            }
            set
            {
                this.DCWSLibVersionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string DCWSCOMVersion
        {
            get
            {
                return this.DCWSCOMVersionField;
            }
            set
            {
                this.DCWSCOMVersionField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.techcenter.com/webservices/datacollection/", ConfigurationName="ServiceReference.HTTPDataCollectionSoap")]
    public interface HTTPDataCollectionSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.techcenter.com/webservices/datacollection/CheckConnectivity", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference.CheckConnectivityResponse> CheckConnectivityAsync(ServiceReference.CheckConnectivityRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.techcenter.com/webservices/datacollection/GetComponentTypeCodes", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference.GetComponentTypeCodesResponse> GetComponentTypeCodesAsync(ServiceReference.GetComponentTypeCodesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.techcenter.com/webservices/datacollection/SaveCDCComponent", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference.SaveCDCComponentResponse> SaveCDCComponentAsync(ServiceReference.SaveCDCComponentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.techcenter.com/webservices/datacollection/SaveCDCTSComponent", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference.SaveCDCTSComponentResponse> SaveCDCTSComponentAsync(ServiceReference.SaveCDCTSComponentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.techcenter.com/webservices/datacollection/SaveCharacterizedComponent", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference.SaveCharacterizedComponentResponse> SaveCharacterizedComponentAsync(ServiceReference.SaveCharacterizedComponentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.techcenter.com/webservices/datacollection/SaveTSCharacterizedComponent" +
            "", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference.SaveTSCharacterizedComponentResponse> SaveTSCharacterizedComponentAsync(ServiceReference.SaveTSCharacterizedComponentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.techcenter.com/webservices/datacollection/SaveCharacterization", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference.SaveCharacterizationResponse> SaveCharacterizationAsync(ServiceReference.SaveCharacterizationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.techcenter.com/webservices/datacollection/SaveTSCharacterization", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference.SaveTSCharacterizationResponse> SaveTSCharacterizationAsync(ServiceReference.SaveTSCharacterizationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.techcenter.com/webservices/datacollection/CheckCDCComponent", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference.CheckCDCComponentResponse> CheckCDCComponentAsync(ServiceReference.CheckCDCComponentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.techcenter.com/webservices/datacollection/GetVersion", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference.GetVersionResponse> GetVersionAsync(ServiceReference.GetVersionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckConnectivityRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckConnectivity", Namespace="http://www.techcenter.com/webservices/datacollection/", Order=0)]
        public ServiceReference.CheckConnectivityRequestBody Body;
        
        public CheckConnectivityRequest()
        {
        }
        
        public CheckConnectivityRequest(ServiceReference.CheckConnectivityRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class CheckConnectivityRequestBody
    {
        
        public CheckConnectivityRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckConnectivityResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckConnectivityResponse", Namespace="http://www.techcenter.com/webservices/datacollection/", Order=0)]
        public ServiceReference.CheckConnectivityResponseBody Body;
        
        public CheckConnectivityResponse()
        {
        }
        
        public CheckConnectivityResponse(ServiceReference.CheckConnectivityResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.techcenter.com/webservices/datacollection/")]
    public partial class CheckConnectivityResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CheckConnectivityResult;
        
        public CheckConnectivityResponseBody()
        {
        }
        
        public CheckConnectivityResponseBody(string CheckConnectivityResult)
        {
            this.CheckConnectivityResult = CheckConnectivityResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetComponentTypeCodesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetComponentTypeCodes", Namespace="http://www.techcenter.com/webservices/datacollection/", Order=0)]
        public ServiceReference.GetComponentTypeCodesRequestBody Body;
        
        public GetComponentTypeCodesRequest()
        {
        }
        
        public GetComponentTypeCodesRequest(ServiceReference.GetComponentTypeCodesRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetComponentTypeCodesRequestBody
    {
        
        public GetComponentTypeCodesRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetComponentTypeCodesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetComponentTypeCodesResponse", Namespace="http://www.techcenter.com/webservices/datacollection/", Order=0)]
        public ServiceReference.GetComponentTypeCodesResponseBody Body;
        
        public GetComponentTypeCodesResponse()
        {
        }
        
        public GetComponentTypeCodesResponse(ServiceReference.GetComponentTypeCodesResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.techcenter.com/webservices/datacollection/")]
    public partial class GetComponentTypeCodesResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference.Items GetComponentTypeCodesResult;
        
        public GetComponentTypeCodesResponseBody()
        {
        }
        
        public GetComponentTypeCodesResponseBody(ServiceReference.Items GetComponentTypeCodesResult)
        {
            this.GetComponentTypeCodesResult = GetComponentTypeCodesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveCDCComponentRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveCDCComponent", Namespace="http://www.techcenter.com/webservices/datacollection/", Order=0)]
        public ServiceReference.SaveCDCComponentRequestBody Body;
        
        public SaveCDCComponentRequest()
        {
        }
        
        public SaveCDCComponentRequest(ServiceReference.SaveCDCComponentRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.techcenter.com/webservices/datacollection/")]
    public partial class SaveCDCComponentRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string vin;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string componentTypeCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string scan1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string scan2;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public bool acceptIfVINNotFound;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public bool acceptIfInvalidScan;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public bool acceptIfWrongComponent;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public bool acceptIfComponentNotRequired;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public bool acceptIfKnownBadComponent;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public bool acceptIfNotVerified;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public bool acceptIfPartAlreadyInstalled;
        
        public SaveCDCComponentRequestBody()
        {
        }
        
        public SaveCDCComponentRequestBody(string vin, string componentTypeCode, string scan1, string scan2, bool acceptIfVINNotFound, bool acceptIfInvalidScan, bool acceptIfWrongComponent, bool acceptIfComponentNotRequired, bool acceptIfKnownBadComponent, bool acceptIfNotVerified, bool acceptIfPartAlreadyInstalled)
        {
            this.vin = vin;
            this.componentTypeCode = componentTypeCode;
            this.scan1 = scan1;
            this.scan2 = scan2;
            this.acceptIfVINNotFound = acceptIfVINNotFound;
            this.acceptIfInvalidScan = acceptIfInvalidScan;
            this.acceptIfWrongComponent = acceptIfWrongComponent;
            this.acceptIfComponentNotRequired = acceptIfComponentNotRequired;
            this.acceptIfKnownBadComponent = acceptIfKnownBadComponent;
            this.acceptIfNotVerified = acceptIfNotVerified;
            this.acceptIfPartAlreadyInstalled = acceptIfPartAlreadyInstalled;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveCDCComponentResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveCDCComponentResponse", Namespace="http://www.techcenter.com/webservices/datacollection/", Order=0)]
        public ServiceReference.SaveCDCComponentResponseBody Body;
        
        public SaveCDCComponentResponse()
        {
        }
        
        public SaveCDCComponentResponse(ServiceReference.SaveCDCComponentResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.techcenter.com/webservices/datacollection/")]
    public partial class SaveCDCComponentResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference.CDCComponent SaveCDCComponentResult;
        
        public SaveCDCComponentResponseBody()
        {
        }
        
        public SaveCDCComponentResponseBody(ServiceReference.CDCComponent SaveCDCComponentResult)
        {
            this.SaveCDCComponentResult = SaveCDCComponentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveCDCTSComponentRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveCDCTSComponent", Namespace="http://www.techcenter.com/webservices/datacollection/", Order=0)]
        public ServiceReference.SaveCDCTSComponentRequestBody Body;
        
        public SaveCDCTSComponentRequest()
        {
        }
        
        public SaveCDCTSComponentRequest(ServiceReference.SaveCDCTSComponentRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.techcenter.com/webservices/datacollection/")]
    public partial class SaveCDCTSComponentRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string vin;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string componentTypeCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string scan1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string scan2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string timestamp;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public bool acceptIfVINNotFound;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public bool acceptIfInvalidScan;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public bool acceptIfWrongComponent;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public bool acceptIfComponentNotRequired;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public bool acceptIfKnownBadComponent;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public bool acceptIfNotVerified;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public bool acceptIfPartAlreadyInstalled;
        
        public SaveCDCTSComponentRequestBody()
        {
        }
        
        public SaveCDCTSComponentRequestBody(string vin, string componentTypeCode, string scan1, string scan2, string timestamp, bool acceptIfVINNotFound, bool acceptIfInvalidScan, bool acceptIfWrongComponent, bool acceptIfComponentNotRequired, bool acceptIfKnownBadComponent, bool acceptIfNotVerified, bool acceptIfPartAlreadyInstalled)
        {
            this.vin = vin;
            this.componentTypeCode = componentTypeCode;
            this.scan1 = scan1;
            this.scan2 = scan2;
            this.timestamp = timestamp;
            this.acceptIfVINNotFound = acceptIfVINNotFound;
            this.acceptIfInvalidScan = acceptIfInvalidScan;
            this.acceptIfWrongComponent = acceptIfWrongComponent;
            this.acceptIfComponentNotRequired = acceptIfComponentNotRequired;
            this.acceptIfKnownBadComponent = acceptIfKnownBadComponent;
            this.acceptIfNotVerified = acceptIfNotVerified;
            this.acceptIfPartAlreadyInstalled = acceptIfPartAlreadyInstalled;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveCDCTSComponentResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveCDCTSComponentResponse", Namespace="http://www.techcenter.com/webservices/datacollection/", Order=0)]
        public ServiceReference.SaveCDCTSComponentResponseBody Body;
        
        public SaveCDCTSComponentResponse()
        {
        }
        
        public SaveCDCTSComponentResponse(ServiceReference.SaveCDCTSComponentResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.techcenter.com/webservices/datacollection/")]
    public partial class SaveCDCTSComponentResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference.CDCComponent SaveCDCTSComponentResult;
        
        public SaveCDCTSComponentResponseBody()
        {
        }
        
        public SaveCDCTSComponentResponseBody(ServiceReference.CDCComponent SaveCDCTSComponentResult)
        {
            this.SaveCDCTSComponentResult = SaveCDCTSComponentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveCharacterizedComponentRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveCharacterizedComponent", Namespace="http://www.techcenter.com/webservices/datacollection/", Order=0)]
        public ServiceReference.SaveCharacterizedComponentRequestBody Body;
        
        public SaveCharacterizedComponentRequest()
        {
        }
        
        public SaveCharacterizedComponentRequest(ServiceReference.SaveCharacterizedComponentRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.techcenter.com/webservices/datacollection/")]
    public partial class SaveCharacterizedComponentRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string vin;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string componentTypeCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string scan1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string scan2;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public bool acceptIfVINNotFound;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public bool acceptIfInvalidScan;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public bool acceptIfWrongComponent;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public bool acceptIfComponentNotRequired;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public bool acceptIfKnownBadComponent;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public bool acceptIfNotVerified;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public bool acceptIfPartAlreadyInstalled;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string characterizationDataType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string characterizationData;
        
        public SaveCharacterizedComponentRequestBody()
        {
        }
        
        public SaveCharacterizedComponentRequestBody(string vin, string componentTypeCode, string scan1, string scan2, bool acceptIfVINNotFound, bool acceptIfInvalidScan, bool acceptIfWrongComponent, bool acceptIfComponentNotRequired, bool acceptIfKnownBadComponent, bool acceptIfNotVerified, bool acceptIfPartAlreadyInstalled, string characterizationDataType, string characterizationData)
        {
            this.vin = vin;
            this.componentTypeCode = componentTypeCode;
            this.scan1 = scan1;
            this.scan2 = scan2;
            this.acceptIfVINNotFound = acceptIfVINNotFound;
            this.acceptIfInvalidScan = acceptIfInvalidScan;
            this.acceptIfWrongComponent = acceptIfWrongComponent;
            this.acceptIfComponentNotRequired = acceptIfComponentNotRequired;
            this.acceptIfKnownBadComponent = acceptIfKnownBadComponent;
            this.acceptIfNotVerified = acceptIfNotVerified;
            this.acceptIfPartAlreadyInstalled = acceptIfPartAlreadyInstalled;
            this.characterizationDataType = characterizationDataType;
            this.characterizationData = characterizationData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveCharacterizedComponentResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveCharacterizedComponentResponse", Namespace="http://www.techcenter.com/webservices/datacollection/", Order=0)]
        public ServiceReference.SaveCharacterizedComponentResponseBody Body;
        
        public SaveCharacterizedComponentResponse()
        {
        }
        
        public SaveCharacterizedComponentResponse(ServiceReference.SaveCharacterizedComponentResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.techcenter.com/webservices/datacollection/")]
    public partial class SaveCharacterizedComponentResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference.CDCComponent SaveCharacterizedComponentResult;
        
        public SaveCharacterizedComponentResponseBody()
        {
        }
        
        public SaveCharacterizedComponentResponseBody(ServiceReference.CDCComponent SaveCharacterizedComponentResult)
        {
            this.SaveCharacterizedComponentResult = SaveCharacterizedComponentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveTSCharacterizedComponentRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveTSCharacterizedComponent", Namespace="http://www.techcenter.com/webservices/datacollection/", Order=0)]
        public ServiceReference.SaveTSCharacterizedComponentRequestBody Body;
        
        public SaveTSCharacterizedComponentRequest()
        {
        }
        
        public SaveTSCharacterizedComponentRequest(ServiceReference.SaveTSCharacterizedComponentRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.techcenter.com/webservices/datacollection/")]
    public partial class SaveTSCharacterizedComponentRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string vin;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string componentTypeCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string scan1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string scan2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string timestamp;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public bool acceptIfVINNotFound;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public bool acceptIfInvalidScan;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public bool acceptIfWrongComponent;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public bool acceptIfComponentNotRequired;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public bool acceptIfKnownBadComponent;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public bool acceptIfNotVerified;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public bool acceptIfPartAlreadyInstalled;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string characterizationDataType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string characterizationData;
        
        public SaveTSCharacterizedComponentRequestBody()
        {
        }
        
        public SaveTSCharacterizedComponentRequestBody(string vin, string componentTypeCode, string scan1, string scan2, string timestamp, bool acceptIfVINNotFound, bool acceptIfInvalidScan, bool acceptIfWrongComponent, bool acceptIfComponentNotRequired, bool acceptIfKnownBadComponent, bool acceptIfNotVerified, bool acceptIfPartAlreadyInstalled, string characterizationDataType, string characterizationData)
        {
            this.vin = vin;
            this.componentTypeCode = componentTypeCode;
            this.scan1 = scan1;
            this.scan2 = scan2;
            this.timestamp = timestamp;
            this.acceptIfVINNotFound = acceptIfVINNotFound;
            this.acceptIfInvalidScan = acceptIfInvalidScan;
            this.acceptIfWrongComponent = acceptIfWrongComponent;
            this.acceptIfComponentNotRequired = acceptIfComponentNotRequired;
            this.acceptIfKnownBadComponent = acceptIfKnownBadComponent;
            this.acceptIfNotVerified = acceptIfNotVerified;
            this.acceptIfPartAlreadyInstalled = acceptIfPartAlreadyInstalled;
            this.characterizationDataType = characterizationDataType;
            this.characterizationData = characterizationData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveTSCharacterizedComponentResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveTSCharacterizedComponentResponse", Namespace="http://www.techcenter.com/webservices/datacollection/", Order=0)]
        public ServiceReference.SaveTSCharacterizedComponentResponseBody Body;
        
        public SaveTSCharacterizedComponentResponse()
        {
        }
        
        public SaveTSCharacterizedComponentResponse(ServiceReference.SaveTSCharacterizedComponentResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.techcenter.com/webservices/datacollection/")]
    public partial class SaveTSCharacterizedComponentResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference.CDCComponent SaveTSCharacterizedComponentResult;
        
        public SaveTSCharacterizedComponentResponseBody()
        {
        }
        
        public SaveTSCharacterizedComponentResponseBody(ServiceReference.CDCComponent SaveTSCharacterizedComponentResult)
        {
            this.SaveTSCharacterizedComponentResult = SaveTSCharacterizedComponentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveCharacterizationRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveCharacterization", Namespace="http://www.techcenter.com/webservices/datacollection/", Order=0)]
        public ServiceReference.SaveCharacterizationRequestBody Body;
        
        public SaveCharacterizationRequest()
        {
        }
        
        public SaveCharacterizationRequest(ServiceReference.SaveCharacterizationRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.techcenter.com/webservices/datacollection/")]
    public partial class SaveCharacterizationRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string vin;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public bool acceptIfVINNotFound;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public bool acceptIfInvalidScan;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public bool acceptIfWrongComponent;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public bool acceptIfComponentNotRequired;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public bool acceptIfKnownBadComponent;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public bool acceptIfNotVerified;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public bool acceptIfPartAlreadyInstalled;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string characterizationDataType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string characterizationData;
        
        public SaveCharacterizationRequestBody()
        {
        }
        
        public SaveCharacterizationRequestBody(string vin, bool acceptIfVINNotFound, bool acceptIfInvalidScan, bool acceptIfWrongComponent, bool acceptIfComponentNotRequired, bool acceptIfKnownBadComponent, bool acceptIfNotVerified, bool acceptIfPartAlreadyInstalled, string characterizationDataType, string characterizationData)
        {
            this.vin = vin;
            this.acceptIfVINNotFound = acceptIfVINNotFound;
            this.acceptIfInvalidScan = acceptIfInvalidScan;
            this.acceptIfWrongComponent = acceptIfWrongComponent;
            this.acceptIfComponentNotRequired = acceptIfComponentNotRequired;
            this.acceptIfKnownBadComponent = acceptIfKnownBadComponent;
            this.acceptIfNotVerified = acceptIfNotVerified;
            this.acceptIfPartAlreadyInstalled = acceptIfPartAlreadyInstalled;
            this.characterizationDataType = characterizationDataType;
            this.characterizationData = characterizationData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveCharacterizationResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveCharacterizationResponse", Namespace="http://www.techcenter.com/webservices/datacollection/", Order=0)]
        public ServiceReference.SaveCharacterizationResponseBody Body;
        
        public SaveCharacterizationResponse()
        {
        }
        
        public SaveCharacterizationResponse(ServiceReference.SaveCharacterizationResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.techcenter.com/webservices/datacollection/")]
    public partial class SaveCharacterizationResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference.CDCComponent SaveCharacterizationResult;
        
        public SaveCharacterizationResponseBody()
        {
        }
        
        public SaveCharacterizationResponseBody(ServiceReference.CDCComponent SaveCharacterizationResult)
        {
            this.SaveCharacterizationResult = SaveCharacterizationResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveTSCharacterizationRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveTSCharacterization", Namespace="http://www.techcenter.com/webservices/datacollection/", Order=0)]
        public ServiceReference.SaveTSCharacterizationRequestBody Body;
        
        public SaveTSCharacterizationRequest()
        {
        }
        
        public SaveTSCharacterizationRequest(ServiceReference.SaveTSCharacterizationRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.techcenter.com/webservices/datacollection/")]
    public partial class SaveTSCharacterizationRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string vin;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string timestamp;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public bool acceptIfVINNotFound;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public bool acceptIfInvalidScan;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public bool acceptIfWrongComponent;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public bool acceptIfComponentNotRequired;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public bool acceptIfKnownBadComponent;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public bool acceptIfNotVerified;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public bool acceptIfPartAlreadyInstalled;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string characterizationDataType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string characterizationData;
        
        public SaveTSCharacterizationRequestBody()
        {
        }
        
        public SaveTSCharacterizationRequestBody(string vin, string timestamp, bool acceptIfVINNotFound, bool acceptIfInvalidScan, bool acceptIfWrongComponent, bool acceptIfComponentNotRequired, bool acceptIfKnownBadComponent, bool acceptIfNotVerified, bool acceptIfPartAlreadyInstalled, string characterizationDataType, string characterizationData)
        {
            this.vin = vin;
            this.timestamp = timestamp;
            this.acceptIfVINNotFound = acceptIfVINNotFound;
            this.acceptIfInvalidScan = acceptIfInvalidScan;
            this.acceptIfWrongComponent = acceptIfWrongComponent;
            this.acceptIfComponentNotRequired = acceptIfComponentNotRequired;
            this.acceptIfKnownBadComponent = acceptIfKnownBadComponent;
            this.acceptIfNotVerified = acceptIfNotVerified;
            this.acceptIfPartAlreadyInstalled = acceptIfPartAlreadyInstalled;
            this.characterizationDataType = characterizationDataType;
            this.characterizationData = characterizationData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveTSCharacterizationResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveTSCharacterizationResponse", Namespace="http://www.techcenter.com/webservices/datacollection/", Order=0)]
        public ServiceReference.SaveTSCharacterizationResponseBody Body;
        
        public SaveTSCharacterizationResponse()
        {
        }
        
        public SaveTSCharacterizationResponse(ServiceReference.SaveTSCharacterizationResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.techcenter.com/webservices/datacollection/")]
    public partial class SaveTSCharacterizationResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference.CDCComponent SaveTSCharacterizationResult;
        
        public SaveTSCharacterizationResponseBody()
        {
        }
        
        public SaveTSCharacterizationResponseBody(ServiceReference.CDCComponent SaveTSCharacterizationResult)
        {
            this.SaveTSCharacterizationResult = SaveTSCharacterizationResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckCDCComponentRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckCDCComponent", Namespace="http://www.techcenter.com/webservices/datacollection/", Order=0)]
        public ServiceReference.CheckCDCComponentRequestBody Body;
        
        public CheckCDCComponentRequest()
        {
        }
        
        public CheckCDCComponentRequest(ServiceReference.CheckCDCComponentRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.techcenter.com/webservices/datacollection/")]
    public partial class CheckCDCComponentRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string vin;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string componentType1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string componentType2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string componentType3;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string componentType4;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string componentType5;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string componentType6;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string componentType7;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string componentType8;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string componentType9;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string componentType10;
        
        public CheckCDCComponentRequestBody()
        {
        }
        
        public CheckCDCComponentRequestBody(string vin, string componentType1, string componentType2, string componentType3, string componentType4, string componentType5, string componentType6, string componentType7, string componentType8, string componentType9, string componentType10)
        {
            this.vin = vin;
            this.componentType1 = componentType1;
            this.componentType2 = componentType2;
            this.componentType3 = componentType3;
            this.componentType4 = componentType4;
            this.componentType5 = componentType5;
            this.componentType6 = componentType6;
            this.componentType7 = componentType7;
            this.componentType8 = componentType8;
            this.componentType9 = componentType9;
            this.componentType10 = componentType10;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckCDCComponentResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckCDCComponentResponse", Namespace="http://www.techcenter.com/webservices/datacollection/", Order=0)]
        public ServiceReference.CheckCDCComponentResponseBody Body;
        
        public CheckCDCComponentResponse()
        {
        }
        
        public CheckCDCComponentResponse(ServiceReference.CheckCDCComponentResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.techcenter.com/webservices/datacollection/")]
    public partial class CheckCDCComponentResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference.CheckComponentResult CheckCDCComponentResult;
        
        public CheckCDCComponentResponseBody()
        {
        }
        
        public CheckCDCComponentResponseBody(ServiceReference.CheckComponentResult CheckCDCComponentResult)
        {
            this.CheckCDCComponentResult = CheckCDCComponentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetVersionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetVersion", Namespace="http://www.techcenter.com/webservices/datacollection/", Order=0)]
        public ServiceReference.GetVersionRequestBody Body;
        
        public GetVersionRequest()
        {
        }
        
        public GetVersionRequest(ServiceReference.GetVersionRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetVersionRequestBody
    {
        
        public GetVersionRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetVersionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetVersionResponse", Namespace="http://www.techcenter.com/webservices/datacollection/", Order=0)]
        public ServiceReference.GetVersionResponseBody Body;
        
        public GetVersionResponse()
        {
        }
        
        public GetVersionResponse(ServiceReference.GetVersionResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.techcenter.com/webservices/datacollection/")]
    public partial class GetVersionResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference.Versions GetVersionResult;
        
        public GetVersionResponseBody()
        {
        }
        
        public GetVersionResponseBody(ServiceReference.Versions GetVersionResult)
        {
            this.GetVersionResult = GetVersionResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface HTTPDataCollectionSoapChannel : ServiceReference.HTTPDataCollectionSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class HTTPDataCollectionSoapClient : System.ServiceModel.ClientBase<ServiceReference.HTTPDataCollectionSoap>, ServiceReference.HTTPDataCollectionSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public HTTPDataCollectionSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(HTTPDataCollectionSoapClient.GetBindingForEndpoint(endpointConfiguration), HTTPDataCollectionSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public HTTPDataCollectionSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(HTTPDataCollectionSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            //
            // this.Endpoint.Binding.OpenTimeout = new System.TimeSpan(0, 0, 5);
            // this.Endpoint.Binding.CloseTimeout = new System.TimeSpan(0, 0, 5);
            // this.Endpoint.Binding.SendTimeout = new System.TimeSpan(0, 0, 5);
            // this.Endpoint.Binding.ReceiveTimeout = new System.TimeSpan(0, 0, 5);
            // System.Console.WriteLine("** set timeout (a) **");
            //
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public HTTPDataCollectionSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(HTTPDataCollectionSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            //
            // this.Endpoint.Binding.OpenTimeout = new System.TimeSpan(0, 0, 5);
            // this.Endpoint.Binding.CloseTimeout = new System.TimeSpan(0, 0, 5);
            // this.Endpoint.Binding.SendTimeout = new System.TimeSpan(0, 0, 5);
            // this.Endpoint.Binding.ReceiveTimeout = new System.TimeSpan(0, 0, 5);
            // System.Console.WriteLine("** set timeout (6) **");
            //
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public HTTPDataCollectionSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.CheckConnectivityResponse> ServiceReference.HTTPDataCollectionSoap.CheckConnectivityAsync(ServiceReference.CheckConnectivityRequest request)
        {
            return base.Channel.CheckConnectivityAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.CheckConnectivityResponse> CheckConnectivityAsync()
        {
            ServiceReference.CheckConnectivityRequest inValue = new ServiceReference.CheckConnectivityRequest();
            inValue.Body = new ServiceReference.CheckConnectivityRequestBody();
            return ((ServiceReference.HTTPDataCollectionSoap)(this)).CheckConnectivityAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.GetComponentTypeCodesResponse> ServiceReference.HTTPDataCollectionSoap.GetComponentTypeCodesAsync(ServiceReference.GetComponentTypeCodesRequest request)
        {
            return base.Channel.GetComponentTypeCodesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.GetComponentTypeCodesResponse> GetComponentTypeCodesAsync()
        {
            ServiceReference.GetComponentTypeCodesRequest inValue = new ServiceReference.GetComponentTypeCodesRequest();
            inValue.Body = new ServiceReference.GetComponentTypeCodesRequestBody();
            return ((ServiceReference.HTTPDataCollectionSoap)(this)).GetComponentTypeCodesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.SaveCDCComponentResponse> ServiceReference.HTTPDataCollectionSoap.SaveCDCComponentAsync(ServiceReference.SaveCDCComponentRequest request)
        {
            return base.Channel.SaveCDCComponentAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.SaveCDCComponentResponse> SaveCDCComponentAsync(string vin, string componentTypeCode, string scan1, string scan2, bool acceptIfVINNotFound, bool acceptIfInvalidScan, bool acceptIfWrongComponent, bool acceptIfComponentNotRequired, bool acceptIfKnownBadComponent, bool acceptIfNotVerified, bool acceptIfPartAlreadyInstalled)
        {
            ServiceReference.SaveCDCComponentRequest inValue = new ServiceReference.SaveCDCComponentRequest();
            inValue.Body = new ServiceReference.SaveCDCComponentRequestBody();
            inValue.Body.vin = vin;
            inValue.Body.componentTypeCode = componentTypeCode;
            inValue.Body.scan1 = scan1;
            inValue.Body.scan2 = scan2;
            inValue.Body.acceptIfVINNotFound = acceptIfVINNotFound;
            inValue.Body.acceptIfInvalidScan = acceptIfInvalidScan;
            inValue.Body.acceptIfWrongComponent = acceptIfWrongComponent;
            inValue.Body.acceptIfComponentNotRequired = acceptIfComponentNotRequired;
            inValue.Body.acceptIfKnownBadComponent = acceptIfKnownBadComponent;
            inValue.Body.acceptIfNotVerified = acceptIfNotVerified;
            inValue.Body.acceptIfPartAlreadyInstalled = acceptIfPartAlreadyInstalled;
            return ((ServiceReference.HTTPDataCollectionSoap)(this)).SaveCDCComponentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.SaveCDCTSComponentResponse> ServiceReference.HTTPDataCollectionSoap.SaveCDCTSComponentAsync(ServiceReference.SaveCDCTSComponentRequest request)
        {
            return base.Channel.SaveCDCTSComponentAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.SaveCDCTSComponentResponse> SaveCDCTSComponentAsync(string vin, string componentTypeCode, string scan1, string scan2, string timestamp, bool acceptIfVINNotFound, bool acceptIfInvalidScan, bool acceptIfWrongComponent, bool acceptIfComponentNotRequired, bool acceptIfKnownBadComponent, bool acceptIfNotVerified, bool acceptIfPartAlreadyInstalled)
        {
            ServiceReference.SaveCDCTSComponentRequest inValue = new ServiceReference.SaveCDCTSComponentRequest();
            inValue.Body = new ServiceReference.SaveCDCTSComponentRequestBody();
            inValue.Body.vin = vin;
            inValue.Body.componentTypeCode = componentTypeCode;
            inValue.Body.scan1 = scan1;
            inValue.Body.scan2 = scan2;
            inValue.Body.timestamp = timestamp;
            inValue.Body.acceptIfVINNotFound = acceptIfVINNotFound;
            inValue.Body.acceptIfInvalidScan = acceptIfInvalidScan;
            inValue.Body.acceptIfWrongComponent = acceptIfWrongComponent;
            inValue.Body.acceptIfComponentNotRequired = acceptIfComponentNotRequired;
            inValue.Body.acceptIfKnownBadComponent = acceptIfKnownBadComponent;
            inValue.Body.acceptIfNotVerified = acceptIfNotVerified;
            inValue.Body.acceptIfPartAlreadyInstalled = acceptIfPartAlreadyInstalled;
            return ((ServiceReference.HTTPDataCollectionSoap)(this)).SaveCDCTSComponentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.SaveCharacterizedComponentResponse> ServiceReference.HTTPDataCollectionSoap.SaveCharacterizedComponentAsync(ServiceReference.SaveCharacterizedComponentRequest request)
        {
            return base.Channel.SaveCharacterizedComponentAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.SaveCharacterizedComponentResponse> SaveCharacterizedComponentAsync(string vin, string componentTypeCode, string scan1, string scan2, bool acceptIfVINNotFound, bool acceptIfInvalidScan, bool acceptIfWrongComponent, bool acceptIfComponentNotRequired, bool acceptIfKnownBadComponent, bool acceptIfNotVerified, bool acceptIfPartAlreadyInstalled, string characterizationDataType, string characterizationData)
        {
            ServiceReference.SaveCharacterizedComponentRequest inValue = new ServiceReference.SaveCharacterizedComponentRequest();
            inValue.Body = new ServiceReference.SaveCharacterizedComponentRequestBody();
            inValue.Body.vin = vin;
            inValue.Body.componentTypeCode = componentTypeCode;
            inValue.Body.scan1 = scan1;
            inValue.Body.scan2 = scan2;
            inValue.Body.acceptIfVINNotFound = acceptIfVINNotFound;
            inValue.Body.acceptIfInvalidScan = acceptIfInvalidScan;
            inValue.Body.acceptIfWrongComponent = acceptIfWrongComponent;
            inValue.Body.acceptIfComponentNotRequired = acceptIfComponentNotRequired;
            inValue.Body.acceptIfKnownBadComponent = acceptIfKnownBadComponent;
            inValue.Body.acceptIfNotVerified = acceptIfNotVerified;
            inValue.Body.acceptIfPartAlreadyInstalled = acceptIfPartAlreadyInstalled;
            inValue.Body.characterizationDataType = characterizationDataType;
            inValue.Body.characterizationData = characterizationData;
            return ((ServiceReference.HTTPDataCollectionSoap)(this)).SaveCharacterizedComponentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.SaveTSCharacterizedComponentResponse> ServiceReference.HTTPDataCollectionSoap.SaveTSCharacterizedComponentAsync(ServiceReference.SaveTSCharacterizedComponentRequest request)
        {
            return base.Channel.SaveTSCharacterizedComponentAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.SaveTSCharacterizedComponentResponse> SaveTSCharacterizedComponentAsync(string vin, string componentTypeCode, string scan1, string scan2, string timestamp, bool acceptIfVINNotFound, bool acceptIfInvalidScan, bool acceptIfWrongComponent, bool acceptIfComponentNotRequired, bool acceptIfKnownBadComponent, bool acceptIfNotVerified, bool acceptIfPartAlreadyInstalled, string characterizationDataType, string characterizationData)
        {
            ServiceReference.SaveTSCharacterizedComponentRequest inValue = new ServiceReference.SaveTSCharacterizedComponentRequest();
            inValue.Body = new ServiceReference.SaveTSCharacterizedComponentRequestBody();
            inValue.Body.vin = vin;
            inValue.Body.componentTypeCode = componentTypeCode;
            inValue.Body.scan1 = scan1;
            inValue.Body.scan2 = scan2;
            inValue.Body.timestamp = timestamp;
            inValue.Body.acceptIfVINNotFound = acceptIfVINNotFound;
            inValue.Body.acceptIfInvalidScan = acceptIfInvalidScan;
            inValue.Body.acceptIfWrongComponent = acceptIfWrongComponent;
            inValue.Body.acceptIfComponentNotRequired = acceptIfComponentNotRequired;
            inValue.Body.acceptIfKnownBadComponent = acceptIfKnownBadComponent;
            inValue.Body.acceptIfNotVerified = acceptIfNotVerified;
            inValue.Body.acceptIfPartAlreadyInstalled = acceptIfPartAlreadyInstalled;
            inValue.Body.characterizationDataType = characterizationDataType;
            inValue.Body.characterizationData = characterizationData;
            return ((ServiceReference.HTTPDataCollectionSoap)(this)).SaveTSCharacterizedComponentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.SaveCharacterizationResponse> ServiceReference.HTTPDataCollectionSoap.SaveCharacterizationAsync(ServiceReference.SaveCharacterizationRequest request)
        {
            return base.Channel.SaveCharacterizationAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.SaveCharacterizationResponse> SaveCharacterizationAsync(string vin, bool acceptIfVINNotFound, bool acceptIfInvalidScan, bool acceptIfWrongComponent, bool acceptIfComponentNotRequired, bool acceptIfKnownBadComponent, bool acceptIfNotVerified, bool acceptIfPartAlreadyInstalled, string characterizationDataType, string characterizationData)
        {
            ServiceReference.SaveCharacterizationRequest inValue = new ServiceReference.SaveCharacterizationRequest();
            inValue.Body = new ServiceReference.SaveCharacterizationRequestBody();
            inValue.Body.vin = vin;
            inValue.Body.acceptIfVINNotFound = acceptIfVINNotFound;
            inValue.Body.acceptIfInvalidScan = acceptIfInvalidScan;
            inValue.Body.acceptIfWrongComponent = acceptIfWrongComponent;
            inValue.Body.acceptIfComponentNotRequired = acceptIfComponentNotRequired;
            inValue.Body.acceptIfKnownBadComponent = acceptIfKnownBadComponent;
            inValue.Body.acceptIfNotVerified = acceptIfNotVerified;
            inValue.Body.acceptIfPartAlreadyInstalled = acceptIfPartAlreadyInstalled;
            inValue.Body.characterizationDataType = characterizationDataType;
            inValue.Body.characterizationData = characterizationData;
            return ((ServiceReference.HTTPDataCollectionSoap)(this)).SaveCharacterizationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.SaveTSCharacterizationResponse> ServiceReference.HTTPDataCollectionSoap.SaveTSCharacterizationAsync(ServiceReference.SaveTSCharacterizationRequest request)
        {
            return base.Channel.SaveTSCharacterizationAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.SaveTSCharacterizationResponse> SaveTSCharacterizationAsync(string vin, string timestamp, bool acceptIfVINNotFound, bool acceptIfInvalidScan, bool acceptIfWrongComponent, bool acceptIfComponentNotRequired, bool acceptIfKnownBadComponent, bool acceptIfNotVerified, bool acceptIfPartAlreadyInstalled, string characterizationDataType, string characterizationData)
        {
            ServiceReference.SaveTSCharacterizationRequest inValue = new ServiceReference.SaveTSCharacterizationRequest();
            inValue.Body = new ServiceReference.SaveTSCharacterizationRequestBody();
            inValue.Body.vin = vin;
            inValue.Body.timestamp = timestamp;
            inValue.Body.acceptIfVINNotFound = acceptIfVINNotFound;
            inValue.Body.acceptIfInvalidScan = acceptIfInvalidScan;
            inValue.Body.acceptIfWrongComponent = acceptIfWrongComponent;
            inValue.Body.acceptIfComponentNotRequired = acceptIfComponentNotRequired;
            inValue.Body.acceptIfKnownBadComponent = acceptIfKnownBadComponent;
            inValue.Body.acceptIfNotVerified = acceptIfNotVerified;
            inValue.Body.acceptIfPartAlreadyInstalled = acceptIfPartAlreadyInstalled;
            inValue.Body.characterizationDataType = characterizationDataType;
            inValue.Body.characterizationData = characterizationData;
            return ((ServiceReference.HTTPDataCollectionSoap)(this)).SaveTSCharacterizationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.CheckCDCComponentResponse> ServiceReference.HTTPDataCollectionSoap.CheckCDCComponentAsync(ServiceReference.CheckCDCComponentRequest request)
        {
            return base.Channel.CheckCDCComponentAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.CheckCDCComponentResponse> CheckCDCComponentAsync(string vin, string componentType1, string componentType2, string componentType3, string componentType4, string componentType5, string componentType6, string componentType7, string componentType8, string componentType9, string componentType10)
        {
            ServiceReference.CheckCDCComponentRequest inValue = new ServiceReference.CheckCDCComponentRequest();
            inValue.Body = new ServiceReference.CheckCDCComponentRequestBody();
            inValue.Body.vin = vin;
            inValue.Body.componentType1 = componentType1;
            inValue.Body.componentType2 = componentType2;
            inValue.Body.componentType3 = componentType3;
            inValue.Body.componentType4 = componentType4;
            inValue.Body.componentType5 = componentType5;
            inValue.Body.componentType6 = componentType6;
            inValue.Body.componentType7 = componentType7;
            inValue.Body.componentType8 = componentType8;
            inValue.Body.componentType9 = componentType9;
            inValue.Body.componentType10 = componentType10;
            return ((ServiceReference.HTTPDataCollectionSoap)(this)).CheckCDCComponentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.GetVersionResponse> ServiceReference.HTTPDataCollectionSoap.GetVersionAsync(ServiceReference.GetVersionRequest request)
        {
            return base.Channel.GetVersionAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.GetVersionResponse> GetVersionAsync()
        {
            ServiceReference.GetVersionRequest inValue = new ServiceReference.GetVersionRequest();
            inValue.Body = new ServiceReference.GetVersionRequestBody();
            return ((ServiceReference.HTTPDataCollectionSoap)(this)).GetVersionAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.HTTPDataCollectionSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.HTTPDataCollectionSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.HTTPDataCollectionSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://19.208.1.178:9092/httpdatacollection/webservice.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.HTTPDataCollectionSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://19.208.1.178:9092/httpdatacollection/webservice.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            HTTPDataCollectionSoap,
            
            HTTPDataCollectionSoap12,
        }
    }
}
