name: buildx

on: 
  push:
    branches:
      - main
  workflow_dispatch:
    
jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -    
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - 
        uses: docker/setup-buildx-action@v2
        id: buildx
        with:
          install: true
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: SKD.Server/Dockerfile
          platforms: linux/arm64,linux/amd64
          tags: paulyk/skd-server:latest
          push: true